package moze_intel.projecte.mixins;

import net.minecraft.TileEntity;
import net.minecraft.TileEntityChest;
import net.minecraft.World;
import net.minecraft.WorldGenDungeons;
import net.minecraft.init.Items;
import net.minecraft.ItemStack;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Dungeon loot addition. Both the main-world dungeons and the Underworld
 * dimension dungeons are generated by WorldGenDungeons, so a single RETURN
 * injection covers them: every generated dungeon chest independently has a
 * 30% chance to contain 1 glowstone dust and a 10% chance to contain 2 glowstone dust
 * (exclusive outcomes: 10% -> 2, 30% -> 1, 60% -> none).
 */
@Mixin(WorldGenDungeons.class)
public abstract class ProjectEDungeonGlowstoneMixin
{
	@Inject(method = "generate", at = @At("RETURN"))
	private void projecte$addGlowstoneLoot(World world, Random rand, int x, int y, int z,
			CallbackInfoReturnable<Boolean> cir)
	{
		if (cir.getReturnValue() == null || !cir.getReturnValue())
		{
			return;
		}
		// The dungeon is a 7x6x7 box centered on (x, y, z); its chests sit
		// inside that volume.
		for (int dx = -3; dx <= 3; dx++)
		{
			for (int dy = -1; dy <= 6; dy++)
			{
				for (int dz = -3; dz <= 3; dz++)
				{
					TileEntity tile = world.getBlockTileEntity(x + dx, y + dy, z + dz);
					if (tile instanceof TileEntityChest)
					{
						addGlowstone((TileEntityChest) tile, rand);
					}
				}
			}
		}
	}

	private static void addGlowstone(TileEntityChest chest, Random rand)
	{
		float roll = rand.nextFloat();
		int count = roll < 0.1F ? 2 : (roll < 0.4F ? 1 : 0);
		if (count <= 0)
		{
			return;
		}
		List<Integer> empty = new ArrayList<>();
		for (int i = 0; i < chest.getSizeInventory(); i++)
		{
			if (chest.getStackInSlot(i) == null)
			{
				empty.add(i);
			}
		}
		if (empty.isEmpty())
		{
			return;
		}
		chest.setInventorySlotContents(empty.get(rand.nextInt(empty.size())), new ItemStack(Items.glowstone_dust, count));
	}
}
